### ISSUE TITLE
O_NOCTTY is not defined on Linux

### ISSUE THREAD

**Issue by eregon** [jnr/jnr-constants#13]
Is this expected? Does it change from system to system?

Also, if one ask for the value it returns a completely wrong value, which is fairly unpractical.
65536 in my case, instead of the right value 256.

I think undefined values should return 0, that would be less surprising.

**Comment by headius** [comment]
The reason for the bogus values is to have a full set of fake values on platforms like JavaPosix that attempt to emulate real behavior. If all the bogus values were zero, you wouldn't be able to use them for anything.

It's the responsibility of the consumer to check if the constant is actually defined on that platform or if it is using a dummy value.

**Comment by eregon** [comment]
I see.
How does one check for it, with `Enum.MYCONSTANT.defined()` ?
