### ISSUE TITLE
Useless socket level constants

### ISSUE THREAD

**Issue by ahorek** [jnr/jnr-constants#73]
```
// SOL_IP not defined
// SOL_TCP not defined
// SOL_UDP not defined
```
they're not defined on any platform, but they should be defined on Linux. I didn't find them manually in my header files, CRuby has to do some nasty tricks under the hood... ?

workaround for puma: https://github.com/puma/puma/pull/2350

**Comment by headius** [comment]
Perhaps since IPPROTO must match, this is a non-issue?

**Comment by ahorek** [comment]
there're SOL constants that don't have an IPPROTO counterpart like SOL_RAW

note that even CRuby doesn't support all of them except these
```
SOL_SOCKET	nil	Socket-level options
SOL_IP	nil	IP socket options
SOL_IPX	nil	IPX socket options
SOL_AX25	nil	AX.25 socket options
SOL_ATALK	nil	AppleTalk socket options
SOL_TCP	nil	TCP socket options
SOL_UDP	nil	UDP socket options
```

anyway, SOL constants are unreliable and very platform-specific.

my PR to Puma will fix the issue https://github.com/puma/puma/pull/2350 so I think we can close this.

**Comment by ahorek** [comment]
Unfortunately, there's a real bug.

see
https://github.com/jruby/jruby/blob/06137d0b3f86f8cf0a3e450fa0638b9c6b496bd4/core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java#L395

here's an example
```
  require 'socket'
  require 'openssl'
  ts = TCPSocket.new 'google.com', 443
  ssl = OpenSSL::SSL::SSLSocket.new(ts, OpenSSL::SSL::SSLContext.new)
  ssl.sync = true
  ssl.connect
  ts.getsockopt(Socket::IPPROTO_IP, 2) # 2 is Socket::IP_TTL which is not supported yet
    =>
      Errno::ENOPROTOOPT (Protocol not available - Protocol not available)
```

this should work on Linux. fix https://github.com/jnr/jnr-constants/pull/74
