### ISSUE TITLE
SO_REUSEPORT is not defined for Linux

### ISSUE THREAD

**Issue by aughr** [jnr/jnr-constants#8]
It's available in more recent kernels. Do you have a way to handle kernel versioning, or is it safe to just add it?

**Comment by headius** [comment]
We can add the value; it would be up to a consumer to confirm it's available on a given platform (but that consumer may be other jnr projects, of course).

**Comment by headius** [comment]
Closing due to age; if this is still valid, please assist us in finishing it up.
