### ISSUE TITLE
Support multi CPU architecture

### ISSUE THREAD

**Issue by shanjiantao** [jnr/jnr-constants#97]
I hava problem with logstash running in mips64el, The performance is that logstash cannot automatically create  an index file. Later I found out that it was a problem with this project. jnr calls the function `open(filename,flags,perm)` of the c library, but the  `openflags` value of different archtiectures are different. You can refer to the definition of the musl c library.

x86 https://git.musl-libc.org/cgit/musl/tree/arch/generic/bits/fcntl.h
arm https://git.musl-libc.org/cgit/musl/tree/arch/arm/bits/fcntl.h
mips64 https://git.musl-libc.org/cgit/musl/tree/arch/mips64/bits/fcntl.h

Currently, the code generated by this project localte at platform/linux, does not  differentiate cpu architecture. Maybe platform/linux/amd64 and platform/linux/mips64  more suitable.

Althouth I solved the problem by local replacement, i think it is not the perfect  solution. So I would like to ask you opinion on this issue.

Attach my locally generated code.
```
diff --git a/src/main/java/jnr/constants/platform/linux/OpenFlags.java b/src/main/java/jnr/constants/platform/linux/OpenFlags.java
index 47dd622..8416823 100644
--- a/src/main/java/jnr/constants/platform/linux/OpenFlags.java
+++ b/src/main/java/jnr/constants/platform/linux/OpenFlags.java
@@ -1,27 +1,27 @@
 // WARNING: This file is autogenerated. DO NOT EDIT!
-// Generated 2018-09-20 16:28:34 +0000
+// Generated 2021-06-01 09:57:03 +0000
 package jnr.constants.platform.linux;
 public enum OpenFlags implements jnr.constants.Constant {
 O_RDONLY(0L),
 O_WRONLY(1L),
 O_RDWR(2L),
 O_ACCMODE(3L),
-O_NONBLOCK(2048L),
-O_APPEND(1024L),
-O_SYNC(1052672L),
+O_NONBLOCK(128L),
+O_APPEND(8L),
+O_SYNC(16400L),
 // O_SHLOCK not defined
 // O_EXLOCK not defined
-O_ASYNC(8192L),
-O_FSYNC(1052672L),
+O_ASYNC(4096L),
+O_FSYNC(16400L),
 O_NOFOLLOW(131072L),
-O_CREAT(64L),
+O_CREAT(256L),
 O_TRUNC(512L),
-O_EXCL(128L),
+O_EXCL(1024L),
 // O_EVTONLY not defined
 O_DIRECTORY(65536L),
 // O_SYMLINK not defined
 // O_BINARY not defined
-O_NOCTTY(256L),
+O_NOCTTY(2048L),
 O_TMPFILE(4259840L),
 O_CLOEXEC(524288L);
 private final long value;
```

**Comment by headius** [comment]
This is a known issue that we have simply not tried to fix yet. See #67 which details the same problem. Do you think you could help? It should not be difficult, but it is not a small amount of work to add arch to the "coordinates" of the constants.

**Comment by shanjiantao** [comment]
Of course, since you think multi-arch should be support, I am very happy to help solve this problem, I will come up with a suitable plan and inplement it as soon as possible.

**Comment by headius** [comment]
> A major problem with this is that there will be many redundant constans

Is this really a problem, though? As I see it, the arch-specific directories are just specialized constant sets for platforms where we know arch is important. The fallback will be for platforms that do not have or do not need their own different set of values.

> Another problem is that how to get environment of these different machines

This is a long-standing problem with no perfect solution, but like jffi we have managed to do ok with user contributions. See also the multi-platform docker/qemu-based build in jffi, which should be able to cover all platforms that Debian supports.

I will have a look at your PR and continue the conversation there!

**Comment by headius** [comment]
Oh could you tell me whether your PR makes jnr-constants work for you? I know there was already some support for arch in jnr-constants, but this would be the first time it was tested.

**Comment by headius** [comment]
The existing code turned out to work well already, and we just needed to be able to generate these files. Thanks to #98 we have that capability plus generated values for a couple platform/arch combinations already.

Thank you for moving this forward!
